server:
  port: 7091

spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:7071}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
