# ============================================================
# registry-server — perfil DEV
# ============================================================

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7081/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    renewal-percent-threshold: 0.49

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
